Description: > 
  This file can be adapted to choose what refinegems should do.
  Note: For windows use \ instead of / for the paths


General Setting: >
  Path to GEM to be investigated

model: '../C_striatum_GEMs/models/Cstr_KC-Na-01.xml' # 'data/e_coli_core.xml' #
entrez_email: 'famke.baeuerle@student.uni-tuebingen.de' # necessary to access NCBI API


Settings for scripts that manipulate the model: >
  They are all split into the ON / OFF switch (TRUE / FALSE) and additional settings like a path to where the new model should be saved.

### Addition of KEGG Pathways as Groups ###
keggpathways: FALSE
kegg_path:  '../C_striatum_GEMs/models/Cstr_KC-Na-01.xml' # path where to save model with KEGG Groups

### SBO-Term Annotation ###
sboterms: FALSE
sbo_path: '../C_striatum_GEMs/models/Cstr_KC-Na-01.xml' # path where to save model with sbo terms

### CarveMe polishing ###
polish_carveme: FALSE
polish_path: '../C_striatum_GEMs/models/Cstr_KC-Na-01.xml' # path where to save the polished model

### Charge correction ###
charge_corr: TRUE
charge_path: '../C_striatum_GEMs/models/Cstr_KC-Na-01.xml'
charge_report_path: '../C_striatum_GEMs/analysis/Cstr_KC-Na-01_multiple_charges.csv'

### Manual Curation ###
man_cur: FALSE
man_cur_type: 'gapfill' # either 'gapfill' or 'metabs'
man_cur_table: '../C_striatum_GEMs/data/manual_curation.xlsx'
man_cur_path: '../C_striatum_GEMs/models/Cstr_17.xml' # path where to save modified model

Settings for scripts that investigate the model: >
  These are only necessary if none of the scripts to manipulate the model are used.

# Settings if you want to compare multiple models
multiple: TRUE
multiple_paths: ['../C_striatum_GEMs/models/Cstr_14.xml', '../C_striatum_GEMs/models/Cstr_15.xml', '../C_striatum_GEMs/models/Cstr_16.xml', '../C_striatum_GEMs/models/Cstr_17.xml'] #, '../C_striatum_GEMs/models/Cstr_KC-Na-01.xml']

# Path to database which contains metabolites present in different media
media_db: 'data/media_db.csv' 

# media to simulate growth from, available: SNM, LB, M9, SMM, CGXII, RPMI
media: ['SNM3', 'RPMI', 'CGXlab'] #'LB', 'M9', 'RPMI', 'CGXII', 'CasA'

# determine whether the memote score should be calculated, default: FALSE
memote: FALSE

# Determine if output file should be created, default: cl
# Filename is set as the models name
output: xlsx #cl, xlsx, csv 
out_path: '../C_striatum_GEMs/analysis/'

# these work only with single models
### Gene comparison ###
genecomp: FALSE # set to False if not needed, only works when gprs are annotated with kegg
# the following is only relevant when turned on
organismid: 'T05059' # C. striatum
gff_file: 'data/cstr.gff' # C. striatum
biggreactions: 'data/bigg_models_reactions.txt'

### ModelSEED comparison ###
modelseed: FALSE # set to False if not needed
modelseedpath: 'data/modelseed_compounds.tsv'