Description: > 
  This file can be adapted to choose what refinegems should do.
  Note: For windows use \ instead of / for the paths


General Setting: >
  Path to GEM to be investigated

model:  '../C_striatum_GEMs/models/Cstr_14.xml' # 'data/e_coli_core.xml' #


Settings for scripts that manipulate the model: >
  They are all split into the ON / OFF switch (TRUE / FALSE) and additional settings like a path to where the new model should be saved.

### Addition of KEGG Pathways as Groups ###
keggpathways: TRUE
kegg_path: '../C_striatum_GEMs/models/Cstr_14_pathways.xml' # path where to save model with KEGG Groups

### SBO-Term Annotation (requires PostgreSQL) ###
sboterms: FALSE
database_user: postgres
database_name: sbo_ann
sbo_path: '../Nextcloud/master_thesis/models/Cstr_17_sbo.xml' # path where to save model with sbo terms

### CarveMe polishing ###
polish_carveme: FALSE
polish_path: 'data/e_test.xml' #'../Nextcloud/master_thesis/models/Cstr_17_genes.xml' # path where to save the polished model
entrez_email: 'famke.baeuerle@student.uni-tuebingen.de'

### Charge correction ###
charge_corr: FALSE
charge_path: '../Nextcloud/master_thesis/models/Cstr_16_charges.xml'


Settings for scripts that investigate the model: >
  These are only necessary if none of the scripts to manipulate the model are used.

# Settings if you want to compare multiple models
multiple: TRUE
multiple_paths: ['../C_striatum_GEMs/models/Cstr_14.xml', '../C_striatum_GEMs/models/Cstr_15.xml', '../C_striatum_GEMs/models/Cstr_16.xml', '../C_striatum_GEMs/models/Cstr_17.xml']

# Path to database which contains metabolites present in different media
media_db: 'data/media_db.csv' 

# media to simulate growth from, available: SNM, LB, M9, SMM, CGXII, RPMI
media: ['SNM3', 'LB', 'M9', 'RPMI']

# determine whether the memote score should be calculated, default: FALSE
memote: FALSE

# Determine if output file should be created, default: cl
# Filename is set as the models name
output: xlsx #cl, xlsx, csv 

# these work only with single models
### Gene comparison ###
genecomp: FALSE # set to False if not needed
# the following is only relevant when turned on
organismid: 'T05059' # C. striatum
gff_file: 'data/cstr.gff' # C. striatum
biggreactions: 'data/bigg_models_reactions.txt'

### ModelSEED comparison ###
modelseed: FALSE # set to False if not needed
modelseedpath: 'data/modelseed_compounds.tsv'