Description: > 
  This file can be adapted to choose what refinegems should do.
  Note: For windows use \ instead of / for the paths


General Setting: >
  Path to GEM to be investigated

model: 'data/e_coli_core.xml' 
# Set the out path for all analysis files
out_path: ''

Settings for scripts that investigate the model: >
  These are only necessary if none of the scripts to manipulate the model are used.

# Set to TRUE if you want pngs that aid in model inevstigation, will be saved to a folder called 'visualization'
visualize: TRUE

# Set the basis medium to simulate growth from
growth_basis: 'minimal_uptake' # 'default_uptake' or 'minimal_uptake'

# Settings if you want to compare multiple models
multiple: FALSE
multiple_paths: # enter as many paths as you need below
  - 'data/e_coli_core.xml'
  - ''
  - ''

# media to simulate growth from, just comment the media you do not want with a #
media: 
  - 'SNM3'
  - 'RPMI'
  - 'CGXlab'
  - 'LB'
  - 'M9'
  - 'CGXII'
  - 'CasA'

# determine whether the memote score should be calculated, default: FALSE
memote: FALSE

# compare metabolites to the ModelSEED database
modelseed: FALSE # set to False if not needed


Settings for scripts that manipulate the model: >
  They are all split into the ON / OFF switch (TRUE / FALSE) and additional settings like a path to where the new model should be saved.

model_out: '' # path and filename to where to save the modified model
entrez_email: '' # necessary to access NCBI API

### Addition of KEGG Pathways as Groups ###
keggpathways: FALSE

### SBO-Term Annotation ###
sboterms: FALSE

### Model polishing ### The database of the model identifiers needs to be specified with 'id_db'
polish: FALSE
id_db: 'BIGG' # Required! 
# Possible identifiers, currently: BiGG & VMH
# For other IDs the `polish` function in `polish.py` might need adjustment
lab_strain: FALSE # Needs to be set to ensure that protein IDs get the 'bqbiol:isHomologTo' qualifier
                  # & to set the locus_tag to the ones obtained by the annotation
protein_fasta: '' # Path to used CarveMe input file, if exists; Needs to be set for lab_strain: True

### Charge correction ###
charge_corr: FALSE

### Manual Curation ###
man_cur: FALSE
man_cur_type: 'gapfill' # either 'gapfill' or 'metabs'
man_cur_table: 'data/manual_curation.xlsx'