Description: > 
  This file can be adapted to choose what refinegems should do.
  Note: For windows use \ instead of / for the paths

General Setting: >
  Path to GEM to be investigated

model: 'Cstr.xml' #'../Nextcloud/master_thesis/models/Cstr_17_sbo.xml' #GCF_002156805.1_ASM215680v1_protein.xml' #'models/cstr_ma.xml' #'models/CStr_20210518.xml' 

Settings for scripts that manipulate the model: >
  They are all split into the ON / OFF switch (TRUE / FALSE) and additional settings like a path to where the new model should be saved.

### Addition of KEGG Pathways as Groups ###
keggpathways: FALSE
kegg_path: ''

### SBO-Term Annotation (requires PostgreSQL) ###
sboterms: FALSE
database_user: postgres
database_name: sbo_ann
sbo_path: '../Nextcloud/master_thesis/models/Cstr_17_sbo.xml' # path where to save model with sbo terms

### CarveMe polishing ###
polish_carveme: FALSE
polish_path: '../Nextcloud/master_thesis/models/Cstr_17_clean.xml' # path where to save polished model

### Charge correction ###
charge_corr: TRUE
charge_path: 'Cstr2.xml'

Settings for scripts that investigate the model: >
  These are only necessary if none of the scripts to manipulate the model are used.

# Path to database which contains metabolites present in different media
media_db: 'media/media_db.csv' 

# media to simulate growth from, available: SNM, LB, M9, SMM, CGXII, RPMI
media: ['SNM3', 'LB', 'M9', 'SMM', 'CGXII', 'RPMI']

# determine whether the memote score should be calculated, default: FALSE
memote: FALSE

# Determine if output file should be created, default: cl
# Filename is set as the models name
output: xlsx #cl, xlsx, csv 

### Gene comparison ###
genecomp: FALSE # set to False if not needed
# the following is only relevant when turned on
organismid: 'T05059' # C. striatum
gff_file: 'genecomp/cstr.gff' # C. striatum
biggreactions: 'genecomp/bigg_models_reactions.txt'

### ModelSEED comparison ###
modelseed: FALSE # set to False if not needed
modelseedpath: 'modelseed/modelseed_compounds.tsv'