# Generally: For windows use \ instead of / for the paths

# Path to GEM to be investigated
model: 'models/CStr_20210518.xml' 

# new filename/path for model with KEGG pathways, default: null means KEGG pathways will not be added
keggpathways: null 

# Requirements: PostgreSQL
sboterms: FALSE
database_user: postgres
database_name: sbo_ann
new_filename: 'cstr_sboann.xml'

### The following inputs are only necessary if neither kegg nor sbo is active ###

# Path to database which contains metabolites present in different media
media_db: 'media/media_db.csv' 

# media to simulate growth from, available: SNM, LB, M9, SMM, CGXII, RPMI
media: ['SNM3', 'LB', 'M9', 'SMM', 'CGXII', 'RPMI']

# determine whether the memote score should be calculated, default: FALSE
memote: FALSE

# Determine if output file should be created, default: cl
# Filename is set as the models name
output: xlsx #cl, xlsx, csv 

### Gene comparison ###
# set to False if not needed
genecomp: FALSE
# the following is only relevant when turned on
organismid: 'T05059' # C. striatum
gff_file: 'genecomp/cstr.gff' # C. striatum
biggreactions: 'genecomp/bigg_models_reactions.txt'
