# Path to GEM to be investigated
model: 'models/CStr_20210518.xml' 

# new filename/path for model with KEGG pathways, default: null means KEGG pathways will not be added
keggpathways: null 

# Requirements: PostgreSQL
# needs database name and user: [database_user, database_name, 'new_filename.xml'] 
sboterms: null 

### The following inputs are only necessary if neither kegg nor sbo is active ###

# Path to database which contains metabolites present in different media
media_db: 'media/media_db.csv' 

# media to simulate growth from, available: SNM, LB, M9, SMM
media: ['SNM3', 'LB', 'M9', 'SMM']

# determine whether the memote score should be calculated, default: FALSE
memote: FALSE

# Determine if output file should be created, default: [command_line, 0]
# for output into an excel file indicate the filename in this format: ['path/to/file/name.xlsx', 1]
# for output of the growth simulation into a csv file: ['path/to/file/name.csv', 2]
output: [command_line, 0]