Description: > 
  This file can be adapted to choose what refinegems should do.
  Note: For windows use \ instead of / for the paths


General Setting: >
  Path to GEM to be investigated

model: '../C_striatum_GEMs/models/Cstr_KC-Na-01.xml' # 'data/e_coli_core.xml' #
entrez_email: 'famke.baeuerle@student.uni-tuebingen.de' # necessary to access NCBI API


Settings for scripts that manipulate the model: >
  They are all split into the ON / OFF switch (TRUE / FALSE) and additional settings like a path to where the new model should be saved.

### Addition of KEGG Pathways as Groups ###
keggpathways: FALSE
kegg_path:  '../C_striatum_GEMs/models/Cstr_KC-Na-01.xml' # path where to save model with KEGG Groups

### SBO-Term Annotation ###
sboterms: FALSE
sbo_path: '../C_striatum_GEMs/models/Cstr_KC-Na-01.xml' # path where to save model with sbo terms

### Model polishing ### The database of the model identifiers needs to be specified with 'id_db'
polish: FALSE
id_db: 'BIGG' # Required! 
# Possible identifiers, currently: BiGG & VMH
# For other IDs the `polish` function in `polish.py` might need adjustment
lab_strain: FALSE # Needs to be set to ensure that protein IDs get the 'bqbiol:isHomologTo' qualifier
                  # & to set the locus_tag to the ones obtained by the annotation
protein_fasta: '' # Path to used CarveMe input file, if exists; Needs to be set for lab_strain: True
polish_path: '../C_striatum_GEMs/models/Cstr_KC-Na-01.xml' # path where to save the polished model

### Charge correction ###
charge_corr: FALSE
charge_path: '../C_striatum_GEMs/models/Cstr_KC-Na-01.xml'
charge_report_path: '../C_striatum_GEMs/analysis/Cstr_KC-Na-01_multiple_charges.csv'

### Manual Curation ###
man_cur: FALSE
man_cur_type: 'gapfill' # either 'gapfill' or 'metabs'
man_cur_table: '../C_striatum_GEMs/data/manual_curation.xlsx'
man_cur_path: '../C_striatum_GEMs/models/Cstr_17.xml' # path where to save modified model

Settings for scripts that investigate the model: >
  These are only necessary if none of the scripts to manipulate the model are used.

# Set the out path for the csv created by multiple and a possible xlsx for model investigation
out_path: '../C_striatum_GEMs/analysis/'

# Set the basis medium to simulate growth from
growth_basis: 'minimal_uptake' # 'default_uptake' or 'minimal_uptake'

# Settings if you want to compare multiple models
multiple: FALSE
multiple_paths: ['../C_striatum_GEMs/models/Cstr_14.xml', '../C_striatum_GEMs/models/Cstr_15.xml', '../C_striatum_GEMs/models/Cstr_16.xml', '../C_striatum_GEMs/models/Cstr_17.xml'] #, '../C_striatum_GEMs/models/Cstr_KC-Na-01.xml']

# Path to database which contains metabolites present in different media
media_db: 'data/media_db.csv' 

# media to simulate growth from, available: SNM, LB, M9, SMM, CGXII, RPMI
media: ['SNM3', 'RPMI', 'CGXlab'] #'LB', 'M9', 'RPMI', 'CGXII', 'CasA'

# determine whether the memote score should be calculated, default: FALSE
memote: FALSE

# Determine if output file for single model should be created, default: cl
# Filename is set as the models name
output: xlsx #cl, xlsx, csv 

# these work only with single models
### Gapfill ###
# All parameters are required for all db_to_compare choices except:
# - organismid which is only required for db_to_compare: 'KEGG'/'KEGG+BioCyc'
# - and biocyc_tables which is not required for 'KEGG'
gapfill_analysis: TRUE
gapfill_analysis_params:
  db_to_compare: 'KEGG'  # One of the choices KEGG|BioCyc|GFF|KEGG+BioCyc
  organismid: 'T05059'  # Needs to be specified for KEGG
  bigg_dbs:
    - 'data/bigg_models_reactions.txt'  # Path to BiGG reactions database
    - 'data/bigg_models_metabolites.txt'  # Path to BiGG metabolites database
  gff_file: 'data/cstr.gff'  # Path to RefSeq GFF file 
  biocyc_files: 
    - 'Path0'  # Path to TXT file containing a SmartTable from BioCyc with the columns 'Accession-2' 'Reaction of gene' (-)
    - 'Path1'  # Path to TXT file containing a SmartTable with all reaction relevant information (*)
    - 'Path2'  # Path to TXT file containing a SmartTable with all metabolite relevant information (+)
    - 'Path3'  # Path to protein FASTA file used as input for CarveMe (Needed to get the protein IDs from the locus tags)
# (-) If the organism is not in BioCyc retrieve a table mapping all reactions in BioCyc to the corresponding sequence
# (*) 'Reaction' 'Reactants of reaction' 'Products of reaction' 'EC-Number' 'Reaction-Direction' 'Spontaneous?'
# (+) 'Compound' 'Object ID' 'Chemical Formula' 'InChI-Key' 'ChEBI'
# For all BioCyc files the order should be the same. If the organism does not occur in the BioCyc database the
# complete tables for reactions can be used with the same columns.

### ModelSEED comparison ###
modelseed: FALSE # set to False if not needed
modelseedpath: 'data/modelseed_compounds.tsv'