name: Update Docs

on: 
  workflow_dispatch:
  push:
    paths:
    - '**.rst'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
       persist-credentials: false
       fetch-depth: 0
      
    - name: Build docs
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
        build-command: "sphinx-build -b html . build"

    - name: Commit docs
      id: commit
      run: |
        git config --local user.email "famke.baeuerle@gmail.com"
        git config --local user.name "famosab"
        git add --all
        if [-z "$(git status --porcelain)"]; then
           echo "::set-output name=push::false"
        else
           git commit -m "Update Docs" -a
           echo "::set-output name=push::true"
        fi
 
    - name: Push changes of the report
      if: steps.commit.outputs.push == 'true'
      uses: ad-m/github-push-action@master
      with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
